services:
  # Backend API Service
  - type: web
    name: user-management-api
    env: node
    buildCommand: cd node-mysql-boilerplate-api && npm install
    startCommand: cd node-mysql-boilerplate-api && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  # Frontend Service
  - type: web
    name: user-management-frontend
    env: node
    buildCommand: cd angular-signup-verification-boilerplate && npm install && npm run build
    startCommand: cd angular-signup-verification-boilerplate && npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        sync: false