services:
  - type: web
    name: user-management-frontend
    env: static
    buildCommand: npm install && npm run build -- --configuration production
    staticPublishPath: dist/angular-signup-verification-boilerplate
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_URL
        value: https://user-management-system-backend-production.up.railway.app
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
